### ISSUE TITLE
Small mistakes in the choosing of FG/BG colors.

### ISSUE THREAD

**Issue by adaptee** [phiggins/konsole-colors-solarized#1]
Hi: 

I think there is a minor mistake in this porting. From my understanding of http://ethanschoonover.com/solarized#usage-development, the following piece of code 

task :dark do
  colors = COMMON.merge(
    'Background'        => SOLARIZED[:base03],
    'BackgroundIntense' => SOLARIZED[:base01],
    'Foreground'        => SOLARIZED[:base00],
    'ForegroundIntense' => SOLARIZED[:base1],
  )

should be changed to : 

task :dark do
  colors = COMMON.merge(
    'Background'        => SOLARIZED[:base03],
    'BackgroundIntense' => SOLARIZED[:base02],
    'Foreground'        => SOLARIZED[:base0],
    'ForegroundIntense' => SOLARIZED[:base1],
  )

Please pay attention to following sentences: 
- "Thus in the case of a dark background colorscheme, the normal relationship for background and body text is base03:base0". 
- "The L_a_b lightness difference between base03:base0 and base02:base1 is identical by design, resulting in identical readability against both normal and highlighted backgrounds. "
- An example use case is folded text in Vim which uses base02 for the background and base1 for the foreground.

The light variant has simiar problem.

**Comment by phiggins** [comment]
When I did the original conversion the documentation was a lot more sparse than it is now, so I'm not surprised I made a few mistakes. I can try to get to this soon, but if you send a pull request this would probably get fixed a lot sooner.

Thanks for reporting this!

**Comment by phiggins** [comment]
This has been merged to master. Thanks!
